### ISSUE TITLE
Ability to load and save the machine state

### ISSUE THREAD

**Issue by duncanamps** [duncanamps/box80#4]
Save the memory as a 64K block and all register states including interrupt mode and interrupt enabled.

**Comment by duncanamps** [comment]
This is now working, however it needs the following refinements:
- [x] Code doesn't have any error checking - if it tries to load garbage, it won't have a happy ending, Issue #32
- [x] Clean up so each module (Processor, SIO, Terminal) can load itself or save itself to an open XML document, Issue #33
- [x] Need to get a `Save | As` as well as just the save, Issue #34
- [x] Put `Save` on a shortcut key (but not Ctrl+S as this might need to be used within the terminal) Issue #31
